esphome:
  name: 'boiler-fart-sensor'
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32c3

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  hardware_uart: USB_SERIAL_JTAG
  level: DEBUG

api:
  encryption: 
    key: !secret api_key

ota:
  safe_mode: true
  password: !secret api_key

sensor:
  - platform: ntc
    id: boiler_flow_temperature
    sensor: flow_resistance_sensor
    calibration:
      b_constant: 3969
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: Flow Temperature

  - platform: resistance
    id: flow_resistance_sensor
    sensor: flow_source_sensor
    configuration: UPSTREAM
    resistor: 10kOhm
    name: Flow Resistance Sensor
    internal: true

  - platform: adc
    id: flow_source_sensor
    pin: 3
    update_interval: 5s
    attenuation: 11db

  - platform: ntc
    id: boiler_return_temperature
    sensor: return_resistance_sensor
    calibration:
      b_constant: 3969
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: Return Temperature

  - platform: resistance
    id: return_resistance_sensor
    sensor: return_source_sensor
    configuration: UPSTREAM
    resistor: 10kOhm
    name: Return Resistance Sensor
    internal: true

  - platform: adc
    id: return_source_sensor
    pin: 4
    update_interval: 5s
    attenuation: 11db