esphome:
  name: 'boiler'
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32c3

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  hardware_uart: USB_SERIAL_JTAG
  level: DEBUG

api:
  encryption: 
    key: !secret api_key

sensor:
  - platform: ntc
    id: boiler_flow_temperature
    sensor: resistance_sensor_1
    calibration:
      b_constant: 3977
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: Flow Temperature

  - platform: ntc
    id: boiler_return_temperature
    sensor: resistance_sensor_2
    calibration:
      b_constant: 3977
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: Return Temperature

  - platform: resistance
    id: resistance_sensor_1
    sensor: source_sensor_1
    configuration: DOWNSTREAM
    resistor: 10kOhm
    name: Resistance Sensor

  - platform: resistance
    id: resistance_sensor_2
    sensor: source_sensor_2
    configuration: DOWNSTREAM
    resistor: 10kOhm
    name: Resistance Sensor

  - platform: adc
    id: source_sensor_1
    pin: 3
    update_interval: 5s
    attenuation: 11db

  - platform: adc
    id: source_sensor_2
    pin: 6
    update_interval: 5s
    attenuation: 11db