esphome:
  name: front-bedroom-co2-sensor
  friendly_name: Front Bedroom CO2

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: arduino
    version: 2.0.5
    platform_version: 5.3.0

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption: 
    key: !secret api_key

# ota:
#   safe_mode: true
#   password: !secret api_key

logger:
  level: DEBUG

i2c:
  sda: 6
  scl: 7

sensor:
  - platform: ee895
    co2:
      name: "Front Bedroom CO2"
      accuracy_decimals: 0
    temperature:
      name: "Temperature"
      accuracy_decimals: 2
    pressure:
      name: "Pressure"
      accuracy_decimals: 1
    address: 0x5F
    update_interval: 15s